# Gerado automaticamente para: {{ project_name }}
FROM python:3.11-slim

WORKDIR /app

# Otimização de cache do Docker
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Porta padrão do FastAPI
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]